language: php

services:
    - docker

matrix:
  include:
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs"
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs --prefer-lowest"
  allow_failures:
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs --prefer-lowest"

install:
  - docker-compose -f test_files/docker-compose.yml up -d
  - travis_retry composer update --prefer-dist $COMPOSER_OPTS
  - php test_files/wait_for_sftp.php

script:
  - FLYSYSTEM_TEST_SFTP=yes FLYSYSTEM_TEST_DANGEROUS_THINGS=yes vendor/bin/phpunit --coverage-text

#after_script:
#  - wget https://scrutinizer-ci.com/ocular.phar
#  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
