language: php

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS="--prefer-lowest"
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs" UPGRADE_AWS_SDK="yes"
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs --prefer-lowest" UPGRADE_AWS_SDK="yes"
  allow_failures:
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs" UPGRADE_AWS_SDK="yes"
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs --prefer-lowest" UPGRADE_AWS_SDK="yes"

install:
  - docker-compose -f test_files/docker-compose.yml up -d
  - travis_retry composer update --prefer-dist $COMPOSER_OPTS
  - eval `ssh-agent` && ssh-add ./test_files/sftp/id_rsa
  - php test_files/wait_for_sftp.php
  - php test_files/wait_for_ftp.php 2121
  - php test_files/wait_for_ftp.php 2122
  - if [[ "${UPGRADE_AWS_SDK}" == "yes" ]]; then composer require --dev --ignore-platform-reqs aws/aws-sdk-php:^3.147.3; fi

script:
  - FLYSYSTEM_TEST_SFTP=yes travis_retry vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyse -l 6 src

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
