---
version: "3"
services:
  sftp:
    restart: always
    image: atmoz/sftp
    volumes:
      - ./sftp/users.conf:/etc/sftp/users.conf
    ports:
      - "2222:22"
    command: foo:pass:::upload
  ftp:
    restart: always
    image: delfer/alpine-ftp-server
    environment:
      USERS: 'foo|pass|/home/foo/upload'
      ADDRESS: 'localhost'
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
  ftpd:
    container_name: ftpd
    restart: always
    environment:
      PUBLICHOST: localhost
      FTP_USER_NAME: foo
      FTP_USER_PASS: pass
      FTP_USER_HOME: /home/foo
    image: stilliard/pure-ftpd
    ports:
      - "2122:21"
      - "30000-30009:30000-30009"
