---
version: "3"
services:
  sftp:
    restart: always
    image: atmoz/sftp
    volumes:
      - ./sftp/users.conf:/etc/sftp/users.conf
    ports:
      - "2222:22"
    command: foo:pass:::upload
  ftp:
    restart: always
    image: delfer/alpine-ftp-server
    environment:
      USERS: 'foo|pass|/home/foo/upload'
      ADDRESS: 'localhost'
    ports:
      - "2121:21"
      - "21000-21010:21000-21010"
